### ISSUE TITLE
Docs not rendering

### ISSUE THREAD

**Issue by abrahamnunes** [ComputationalPsychiatry/fitr#17]
The documentation written and compiled with sphinx is not rendering correctly. 

@ARudiuk could you have a look to see what might be happening?

Many of our functions are decently documented, but for whatever reason I can't get them to render in sphinx with autodoc.

**Comment by ARudiuk** [comment]
Can look at it!

**Comment by abrahamnunes** [comment]
Thanks man!

------------------------------
Abraham Nunes

Resident Physician
Department of Psychiatry
Dalhousie University
Halifax, NS

On April 4, 2017 at 5:46:44 PM, Alexander Rudiuk (notifications@github.com)
wrote:

Can look at it!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ComputationalPsychiatry/fitr/issues/17#issuecomment-291626860>,
or mute the thread

**Comment by abrahamnunes** [comment]
Fixed the rendering issue. See pull request for more details
