### ISSUE TITLE
Package for PyPI

### ISSUE THREAD

**Issue by abrahamnunes** [ComputationalPsychiatry/fitr#2]
We need to be able to install this using pip as a proper package. In it's current form, it is more like a Matlab toolbox...

**Comment by ARudiuk** [comment]
- [ ] Check rules around formatting

**Comment by ARudiuk** [comment]
pypi prefers the README to be in .rst instead of .md, but i'll try it with .md

**Comment by ARudiuk** [comment]
The classifiers portion seems to require values from a previous list of value found here,
https://pypi.python.org/pypi?%3Aaction=list_classifiers

I was wondering what your opinion on the following is @abrahamnunes 
- Intended Audience
- Topic

I am also going to add python 2.7.13 to the list of supported python versions as that is the one I am currently using, if that's alright.

**Comment by abrahamnunes** [comment]
**Re: intended audience**
- Science/Research

**Re: Topic**
- Topic :: Scientific/Engineering
- Topic :: Scientific/Engineering :: Medical Science Apps.
- Topic :: Scientific/Engineering :: Artificial Intelligence

**Re: Python 2.7**
- That's great. I pretty much exclusively use 3.5, so haven't tested at all on 2.7 myself

**Comment by ARudiuk** [comment]
As far as I understand there is no data that needs to be installed alongside the scripts yet, so i'm going to leave that section blank

**Comment by ARudiuk** [comment]
Is it alright if I change the README to .rst from .md? @abrahamnunes

**Comment by abrahamnunes** [comment]
Definitely

Abraham Nunes

Resident Physician
Department of Psychiatry
Dalhousie University
Halifax, NS, Canada
Tel: (902) 292-8297
Email: nunes@dal.ca

**Comment by ARudiuk** [comment]
How does this release on the test server look? @abrahamnunes 

https://testpypi.python.org/pypi/fitr/0.0.1.dev1

**Comment by abrahamnunes** [comment]
Looks good, but the code portion should be updated since it presently assumes one is merely working within the fitr folder as the main directory.

**Comment by ARudiuk** [comment]
I'll make a pull request out of it, and we can highlight what needs to
change in the documentation.
