### ISSUE TITLE
Moving to Python 3

### ISSUE THREAD

**Issue by abrahamnunes** [ComputationalPsychiatry/fitr#37]
I'm going to drop support for Python 2 in the next merge, and move to exclusive development in Python 3. Pretty much all libraries that fitr uses have robust Python3 implementations, and Python2 is nearing end of life. Consequently, I think spending further time supporting python2 in fitr is suboptimal.

If there are significant concerns about this, please let me know.

**Comment by ARudiuk** [comment]
I think Python 2 support goes until 2020, but we can drop it now if you want. Should be pretty simple for most people to install Python 3!
